### ISSUE TITLE
Can't load back the optimized pil.

### ISSUE THREAD

**Issue by lvella** [powdr-labs/powdr#497]
Tried to run powdr from the `vec_median_opt.pil` (the optimized pil output by running `vec_median` test):
```
$ RUST_BACKTRACE=1 cargo run --release -- pil -o tmp -i 5,11,15,75,6,5,1,4,7,3,2,9,2 tmp/vec_median_opt.pil
```

The parser failed to load the pil file with the following error:

```
Error parsing .pil file:
error: Unrecognized token `(` found at 4064:4065
Expected one of "%", "&", ")", "*", "**", "+", ",", "-", "/", ";", "<<", "=", "=>", ">>", "]", "^", "in", "is", "{", "|" or "}"
    ┌─ /home/lucas/ef/src/powdr/tmp/vec_median_opt.pil:134:35
    │
134 │     col fixed LAST(i) { main.FIRST((i + 1)) };
    │                                   ^

thread 'main' panicked at 'explicit panic', /home/lucas/ef/src/powdr/pil_analyzer/src/pil_analyzer.rs:127:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: pil_analyzer::pil_analyzer::PILContext<T>::process_file_contents
   4: pil_analyzer::pil_analyzer::PILContext<T>::process_file
   5: compiler::compile_pil_or_asm
   6: powdr::run_command
   7: powdr::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by leonardoalt** [comment]
Yea this is related to these
https://github.com/powdr-labs/powdr/issues/367
https://github.com/powdr-labs/powdr/issues/368

**Comment by chriseth** [comment]
Closing, tracked in #367
