### ISSUE TITLE
Run Taiko Client on Powdr

### ISSUE THREAD

**Issue by CeciliaZ030** [powdr-labs/powdr#850]
TODOs:

- [ ] Run [EVM](https://github.com/powdr-labs/powdr/blob/main/riscv/tests/riscv_data/evm/src/lib.rs) in [riscv/tests/riscv.rs](https://github.com/powdr-labs/powdr/blob/main/riscv/tests/riscv.rs). Latest attempt did not work with error in  `riscv_executor::execute_ast` in main branch:
```
thread 'test_evm' panicked at /home/phoebe/projects/powdr/riscv_executor/src/lib.rs:757:66:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a96d57bdb6d2bb6d233d7d5aaefc2995ab99be01/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/a96d57bdb6d2bb6d233d7d5aaefc2995ab99be01/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/a96d57bdb6d2bb6d233d7d5aaefc2995ab99be01/library/core/src/panicking.rs:208:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/a96d57bdb6d2bb6d233d7d5aaefc2995ab99be01/library/core/src/slice/index.rs:255:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/a96d57bdb6d2bb6d233d7d5aaefc2995ab99be01/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/a96d57bdb6d2bb6d233d7d5aaefc2995ab99be01/library/alloc/src/vec/mod.rs:2770:9
   6: riscv_executor::Executor<F>::eval_expression
             at /home/phoebe/projects/powdr/riscv_executor/src/lib.rs:757:66
   7: riscv_executor::execute_ast
             at /home/phoebe/projects/powdr/riscv_executor/src/lib.rs:820:31
   8: riscv::common::verify_riscv_asm_string
             at ./tests/common/mod.rs:17:5
   9: riscv::verify_riscv_crate
             at ./tests/riscv.rs:232:5
  10: riscv::test_evm
             at ./tests/riscv.rs:22:5
  11: riscv::test_evm::{{closure}}
             at ./tests/riscv.rs:20:14
```
- [ ] Port `TaikoBlockBuilder` to integration test with mock input data: https://github.com/CeciliaZ030/zeth/blob/8551ed4cf23f02b5d220d41389b423e88324a224/raiko-guest-powdr/src/one_shot.rs#L98
- [ ] Figure out how to compact Taiko specific public input to Powdr's witness input.
- [ ] Integrate Powdr's continuation design
- [ ] Serve proof context from raiko-host by implementing https://github.com/taikoxyz/zeth/pull/2

@leonardoalt If you can help us with the first step running the revm that'd be amazing! 😊

**Comment by leonardoalt** [comment]
This is great!

@CeciliaZ030 for the first EVM test, how did you run it? With cargo run or test? My guess is that the input bytecode is missing or wrong.

With cargo run:
`cargo run --release rust riscv/tests/riscv_data/evm/ -o /tmp/test_revm -f -i "11,97,2,154,96,0,82,96,32,96,0,243"`

With cargo test, the inputs were indeed broken and I fixed it here: https://github.com/powdr-labs/powdr/pull/851 . If you checkout that branch,  you can run it directly with

`cargo test --release test_evm -- --ignored --nocapture --exact`

I think that test also runs the PIL witness verifier from pilcom, so you'll need to clone https://github.com/0xPolygonHermez/pilcom and run `export PILCOM=<cloned pilcom dir>` before running `cargo test` above.

For the second item, you can take a look here at how to call powdr's RISCV executor (needed for continuations and before witness generation):

https://github.com/powdr-labs/powdr_revm/blob/main/bin/src/main.rs#L57

Also note that we're currently refactoring some of the public API entry-points, so my suggestion above might be updated soon.

**Comment by CeciliaZ030** [comment]
Thanks very much! @leonardoalt 
With `cargo run --release rust riscv/tests/riscv_data/evm/ -o /tmp/test_revm -f -i "11,97,2,154,96,0,82,96,32,96,0,243"`, it runs to the witness generation but it fails at some row with constrain not satisfied:
https://github.com/powdr-labs/powdr/blob/4ce94ce4556c7c56501967770fb58e3b67532cc3/executor/src/witgen/vm_processor.rs#L140

Not sure if this is intended?

**Comment by CeciliaZ030** [comment]
Hi @leonardoalt, now I'm running from my fork of the latest Zeth, because our `BlockBuilder` is modified within Zeth. Pls check this out https://github.com/CeciliaZ030/zeth/pull/1
Now the I've had a RICS-V binary compiled with all `no_std` dependency, but during ASM compilation I have this issue:
```
    Finished release [optimized] target(s) in 4.77s
The assembly code references an external routine / label that is not available:
__runtime_start
thread 'main' panicked at /home/phoebe/.cargo/git/checkouts/powdr-5ad669c296f4e377/8b00b33/asm_utils/src/reachability.rs:96:13:
explicit panic
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: asm_utils::reachability::find_reachable_labels
             at /home/phoebe/.cargo/git/checkouts/powdr-5ad669c296f4e377/8b00b33/asm_utils/src/reachability.rs:96:13
   4: asm_utils::reachability::filter_reachable_from
             at /home/phoebe/.cargo/git/checkouts/powdr-5ad669c296f4e377/8b00b33/asm_utils/src/reachability.rs:24:9
   5: riscv::compiler::compile
             at /home/phoebe/.cargo/git/checkouts/powdr-5ad669c296f4e377/8b00b33/riscv/src/compiler.rs:127:5
   6: riscv::compile_riscv_asm_bundle
             at /home/phoebe/.cargo/git/checkouts/powdr-5ad669c296f4e377/8b00b33/riscv/src/lib.rs:107:21
   7: riscv::compile_rust
             at /home/phoebe/.cargo/git/checkouts/powdr-5ad669c296f4e377/8b00b33/riscv/src/lib.rs:72:5
   8: bin_powdr::main
             at ./bin-powdr/src/main.rs:7:41
   9: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Basically my binary is missing label `__runtime_start`? Not sure if it's a RISC-V compiler versioning issue...

**Comment by leonardoalt** [comment]
@CeciliaZ030 yea we need to call the continuations library instead of calling verify there directly. Let me open a PR to your code

**Comment by leonardoalt** [comment]
@CeciliaZ030 what does the second item entail on our side?
